config/routes.rb
Rails.application.routes.draw do
  devise_for :users do
    get "/users/sign_out" => "devise/sessions#destroy"
  end
  resources :posts do 
    resources :comments
  end
  root "posts#index"
  get "/about", to: "pages#about"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  validates :tittle, presence: true, length: { minimum:5 }
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_post_comment, only: [:edit, :update, :show, :destroy]
    
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)

    redirect_to post_path(@post)
  end

  def destroy
    @comment = @post.comments.find(params[:id])
    @comment.destroy

    redirect_to post_path(@post)
  end


  private

    def find_post_comment
      @post = Post.find(params[:post_id])
    end

    def comment_params
      params.require(:comment).permit(:name, :body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:edit, :update, :show, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  
  def index
    @posts = Post.all.order(:created_at, :DESC)
  end

  def new
    @post = Post.new
  end
  
  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post
    else
      render "new"
    end
  end  

  def show
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render "edit"
    end
  end

  def destroy
    @post.destroy
    flash.now[:notice] = 'Post deleted'
    redirect_to root_path
  end 

  private

    def find_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:tittle, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
  <div class="comment_content">
    <p class="comment_name"><em><%= comment.name %></em></p>
    <p class="comment_body"><%= comment.body %></p>
    <p class="comment_tittle"><%= time_ago_in_words(comment.created_at) %> Ago</p>
  </div>  
  <% if user_signed_in? %>
    <p><%= button_to "Delete", [comment.post, comment], method: :delete, class: "button", data: { confirm: "Are you sure?" } %></p>
  <% end %> 
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    <%= f.label :name %><br>    
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tumblr</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css2?family=Raleway:ital,wght@1,100&display=swap' %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= javascript_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="sidebar">
      <ul>
        <li class="category"><%=link_to "Tumblr", root_path %></li>
        <li><%= link_to "Tumblr", root_path %></li>
        <li><%= link_to "About", about_path %></li>
      </ul>      
      <% if !user_signed_in? %>
        <p class="sign_in"><%= link_to "User Login", new_user_session_path %>
      <% end %>      
    </div>

    <div id="main_content">
      <div id="header">
      
      <% if current_page?(root_path) %>
        <p>Post Feed</p>
      <% elsif current_page?(about_path) %>
        <p>My site</p>
      <% else %>
        <%= link_to "Back to Post Feed", root_path %>
      <% end %>
      
      <% if user_signed_in? %>
        <div class="buttons">
          <button class="button"><%= link_to "Make post", new_post_path %></button>
          <button class="button"><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></button>
        </div>
      <% end %>
      </div>
      <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert") %>
      <% end %>
  
      <%= yield %>  
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<div id="page_wrapper">
  <div id="profile_image">
    <%= image_tag "profile.jpeg" %>
  </div>
  <div id="content">
    <h1>It's Mr. Stick Figure</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc felis odio, ultrices vel pretium ut, ornare in lectus. Sed dignissim scelerisque nulla eu euismod. In vitae pretium elit. Curabitur scelerisque porttitor vehicula. Vivamus scelerisque mi a dui interdum, a ultrices felis aliquet. Sed vel eros semper, vulputate eros lacinia, interdum lorem. Sed porttitor elit nec eleifend pretium. Quisque sit amet ante ac odio pharetra consequat.</p>
  </div>
</div>

app/views/posts/_form.html.erb
  <%= form_for @post do |f| %>
    <% if @post.errors.any? %>
      <div id="errors">
        <h2><%= pluralize(@post.errors.count, "error") %> stopped this post saving</h2>
        <ul>
          <% @post.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <p>
    <%= f.label :tittle %><br>
    <%= f.text_field :tittle %>
    </p>
    
    <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
    </p>

    <p>
      <%= f.submit %>
    </p>
  <% end %>

app/views/posts/edit.html.erb
<div id="page_wrapper">
  <h1> Fix Post </h1>

  <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <div class="post_wrapper">
    <h2 class="tittle"><%= link_to post.tittle, post %></h2>
    <p class="body"><%= truncate(post.body, length:100) %>
    <p class="date"><%= time_ago_in_words(post.created_at) %> ago</p>
  </div>
<% end %>

app/views/posts/new.html.erb
<div id="page_wrapper">
  <h1> Make something </h1>

  <%= form_for :post, url: posts_path do |f| %>
    <% if @post.errors.any? %>
      <div id="errors">
        <h2><%= pluralize(@post.errors.count, "error") %> stopped this post saving</h2>
        <ul>
          <% @post.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <p>
    <%= f.label :tittle %><br>
    <%= f.text_field :tittle %>
    </p>
    
    <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
    </p>

    <p>
      <%= f.submit %>
    </p>
  <% end %>
</div>

app/views/posts/show.html.erb
<div id="post_content">
  <h1 class="tittle">
    <%= @post.tittle %>
  </h1>

  <p class="date">
    Submitted <%= time_ago_in_words(@post.created_at) %> ago
    <% if user_signed_in? %>    
      |<%= link_to "Edit", edit_post_path(@post) %> |      
      <%= button_to 'Delete', post_path(@post.id), :confirm => 'Are you sure?', :method => :delete %>
    <% end %>
  </p>

  <p class="body">
    <%= @post.body %>
  </p>

  <div id="comments">
    <h2><%= @post.comments.count %> Comments</h2>
    <%= render @post.comments %>
    <h3> Join Discussion: </h3>
    <%= render "comments/form" %>
  </div>
</div>